spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-jpa?autoReconnect=true&useSSL=false
    username: root
    password: ubo361.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true